spatie/laravel-settings

- README.md
The tag of the config is called `settings` in the `LaravelSettingsServiceProvider`. The README now reflects this.
(another options would be to make the code reflect the README of course, if you prefer :) )
> Fix config file tag

- src/Console/MakeSettingsMigrationCommand.php
```
file_put_contents( {{ PATH }}): failed to open stream: No such file or directory
```
With a clean install and following the docs I ran into the above issue, this can be solved using the Filesystem
> Ensure that database migration path exists

- README.md
- src/Console/MakeSettingsMigrationCommand.php
Fixed an incorrect path in the stub to make a settings migrations command, also updated references in the readme.
`use Spatie\LaravelSettings\SettingsMigration;` --> `use Spatie\LaravelSettings\Migrations\SettingsMigration;`
> Fixes package path in make migration command

- README.md
Fixes `regular_ype` to `regular_type`
> Fix simple typo in documentation

- README.md
Hi,
This fixes a bad method label in the sample code in section "Operations in group".
Regards,
Aurelien
> Fix bad method label in Readme

- src/Events/SavingSettings.php
- src/Settings.php
- tests/SettingsTest.php
This goes to add the original properties into the settings class to allow activity logging. This takes the simpler approach like eloquent takes with just having a copy of the original properties alongside the settings rather than an explicit database call to reload properties we could already have.
> add original properties for easier logging

- src/Migrations/SettingsMigrator.php
- tests/SettingsMigratorTest.php
Hi @rubenvanassche ,
This is my PR following https://github.com/spatie/laravel-settings/discussions/49 .
This make the migrations 'castable' using the global casts.
NOTES: 
* As this change the Type passed to the update's closure, this might be concidered as breaking change.
* There is many use of `optional()` helper, those could be replaced by `?->` when php 8 is only supported.
* To reduce breaking change casts are only set on objects created or updated.
* Since now we have access to settings classes in migrations, we could enforce that groups and names match existing group class and there properties (to detect typos or non exting group/properties), maybe as a futur feature...
> Add cast on migration

- src/SettingsContainer.php
When the config is already cached, it is missing the `settings.auto_discover_settings` setting.
So `config('settings.auto_discover_settings')` returns `null`.
This produces the error ` Spatie\LaravelSettings\Support\DiscoverSettings::within(): Argument #1 ($directories) must be of type array, null given`.
The within function of DiscoverSettings only accepts an array, so I added an array as the default value.
it is also possible to change the function to `within(array $directories = [])`. I don't know what is better.
> Added empty array as fallback for settings.auto_discover_settings.

- src/Support/DiscoverSettings.php
Hi, 
I have made abstract class to extend in local project
```
app
- Setting
- BaseSetting.php < - base setting
- MySetting.php < --- setting
```
```php
<?php
namespace App\Setting;
use Spatie\LaravelSettings\Settings;
abstract class BaseSetting extends Settings
{
// all setting class level will inherit
}
```
```php
<?php
namespace App\Setting;
class MySetting extends BaseSetting
{
public ?MyType $my_field = null;
public static function group(): string
{
return 'my-group';
}
}
```
because of this, it will return on updating using migrator
```php
$settingMigrator = app(SettingsMigrator::class);
$settingMigrator->inGroup(MySetting::group(), function (SettingsBlueprint $settingsBlueprint) {
foreach (
[
'my_field' => <value>,
// ............
] as $field => $data
) { …
```
> Ignore abstract class when discovering

- .github/workflows/php-cs-fixer.yml
- .github/workflows/run-tests.yml
- .github/workflows/update-changelog.yml
- composer.json
This PR adds PHP 8.1 support to the tests workflow.
Additionally, it:
- **drops support for Laravel 7.x**
- bumps dependency versions to latest in `composer.json`
- adds the update changelog workflow
- bumps github action versions where appropriate
_This repository needs its primary branch renamed from `master` to `main`._
> Add PHP 8.1 Support

- src/Migrations/SettingsBlueprint.php
- src/Migrations/SettingsMigrator.php
With this PR we can now leave out the second param when creating migrations (it defaults to `null`).
```php
$this->migrator->add('app_name'); // it's the same as $this->migrator->add('app_name', null);
// and in migrator blueprint also
$blueprint->add('app_name');
```
I've also ajdusted `encrypted` counterparts.
> Added default nullable column to migrator

- composer.json
- src/LaravelSettingsServiceProvider.php
- src/SettingsContainer.php
Using singletons for settings classes can cause the settings instance to remain in the IOC container over multiple jobs (Horizon) or multiple requests (Octane). This isn't an issue for most projects, as settings don't randomly change every request. However, in a multi-tenancy environment the loaded settings different every job and every request, based on the tenant. In this case we do not want to re-use a settings instance that's still around in the IOC container from the previous request.
TL;DR: switching `singleton` to `scoped` causes the settings class instances to be refreshed every request & every job
https://laravel.com/docs/8.x/container#binding-scoped
> Switch to using scoped instances instead of singletons

- database/migrations/create_settings_table.php.stub
There was no down function in the migration stub. Added rollback code.
> Fixed database rollback bug

- .github/workflows/run-tests.yml
- CHANGELOG.md
- composer.json
Had some time this morning to create a pull request for the issue I've created yesterday. I think this is the easiest way to go because the dto package is not really required as a root dependency. I've made it optional so people can still use it.
We could also completely remove the dependency but that would be a pretty big breaking change.
Closes #160
> Remove deprecated package

- README.md
- config/settings.php
- src/Console/MakeSettingCommand.php
- src/LaravelSettingsServiceProvider.php
- tests/Console/MakeSettingCommandTest.php
Well, I'm too lazy to create a new class whenever I need to add a new group of settings😂😂. This feature was first introduced by @egyjs in #126. But because of inactivity, it was closed without being merged. 
This PR adds a new `make:setting` command, that is functional and its test included.
> Create new Setting Command

- src/Console/MakeSettingsMigrationCommand.php
- tests/Console/MakeSettingsMigrationCommandTest.php
Previously, no message was displayed to the user after executing the ``make:settings-migration`` command, but now, after executing the command, a message including the result and the location of the created file is displayed to the user.
> Show message and target path after setting migration created

- src/Console/MakeSettingCommand.php
1. I've updated `MakeSettingCommand::getNamespace` to follow Laravel's namespace convention. All namespace names within the hierarchy will be capitalized.
2. `MakeSettingCommand::getNamespace` will now return the namespace alone, rather than returning the full line of code intended for the final file. The stub has been edited to take care of the surrounding code, which is how Laravel handles inserting the namespace in its generator commands.
3. `MakeSettingCommand::resolveSettingsPath` will now reference the correct config option: `settings.setting_class_path`.
> Follow Laravel's namespace convention in MakeSettingCommand.php

- README.md
- database/migrations/create_settings_table.php.stub
- src/Migrations/SettingsMigrator.php
- src/SettingsMapper.php
- src/SettingsRepositories/DatabaseSettingsRepository.php
- src/SettingsRepositories/RedisSettingsRepository.php
- src/SettingsRepositories/SettingsRepository.php
- tests/Pest.php
- tests/SettingsRepositories/DatabaseSettingsRepositoryTest.php
- tests/SettingsRepositories/RedisSettingsRepositoryTest.php
- tests/SettingsTest.php
The purpose of this pull request is to improve the performance of database updates discussed [here](https://github.com/spatie/laravel-settings/discussions/212), by grouping records by their respective groups and performing batch updates on each group. Instead of saving each record in a single query, this approach sends a single request per group, resulting in faster and more efficient updates at the database level.
It is safe to use this feature because it includes error handling that falls back to the original save logic in the event of any issues. This ensures that data is not lost and that the application can continue to function correctly even if an error occurs during the save process.
> Introduce new batch update for settings reduces the number of queries sent to the database and redis

- README.md
- UPGRADING.md
- database/migrations/create_settings_table.php.stub
This PR attempts to resolve #217
Technically speaking, just the changes to the upgrade guide are needed. I have added a separate commit for removing the now unnecessary index from the stub migration for the reasons I detail in the linked issue.
I don't think this qualifies as a breaking change, but I can remove that commit if you'd prefer to retain both indexes. I can also remove this line from the example migration in the UPDGRADING.md.
> Add missing upgrade steps

- README.md
- src/LaravelSettingsServiceProvider.php
Hey there,
I found that "settings" as a publication tag for a **config** file is rather confusing, so...
[Enhancement] Changes include:
- Changed the service provider's tag name for config file publication
- Adjusted the tag name in [README.md]
That's it.
> Change provider tag name for config

- src/SettingsRepositories/DatabaseSettingsRepository.php
Tries to use `Illuminate\Database\Eloquent\Casts\Json` if it is available and falls back to native `json_encode`/`json_decode` otherwise.
This change allows the usage of custom JSON serializers or custom serialization options by defining the following in a service provider:
```php
Json::encodeUsing(fn ($value) => json_encode($value, JSON_UNESCAPED_UNICODE));
```
> Use Illuminate\Database\Eloquent\Casts\Json if possible

- src/LaravelSettingsServiceProvider.php
- tests/Migrations/2018_11_21_091111_create_fake_anonymous_class_with_parentheses_settings.php
- tests/SettingsTest.php
Currently, the migration class matching will not match when `()` is properly added to anonymous migration classes. This will make sure that that and all other scenarios are matched.
> Improved Migration Match

- composer.json
Starting with Larastan 2.7.0, the Larastan repository will now be managed under the Larastan organization.
> Update composer.json to use Larastan Org

- src/Console/MakeSettingCommand.php
I'm working with lando (docker) and there the "src" folder is mounted to "/app".
This is what my path looks like:
/app/app/Settings
Currently the make command replaces all occurrences of base path which results in a wrong namespace "Settings".
> fix when base path is app path

- src/SettingsRepositories/DatabaseSettingsRepository.php
Recent changes in `src/SettingsRepository/DatabaseSettingsRepository` which introduced `mixed` type hint introduce breaking changes with project running PHP 7.4. This PR attempt to solve the issue by removing the type hint and move them to their respective docblock.
Fixes #263
> [3.x] Fix PHP 7.4 Compatibilty

- README.md
There are a few stubs that are out of date, for example. the migration has changed from
```php
class CreateGeneralSettings extends SettingsMigration
```
to
```php
return new class extends SettingsMigration
```
and the config has also changed a little too.
Thanks for the package and keep up the good work you lot do :-)
> Change out of date stubs in README

- src/SettingsCasts/DateTimeInterfaceCast.php
- tests/SettingsTest.php
Only `Carbon\Carbon` is now supported, but given that this is a Laravel package it'd be good to also support casting to `Illuminate\Support\Carbon`.
> Support Illuminate\Support\Carbon as cast

- README.md
- src/SettingsMapper.php
- tests/SettingsTest.php
- tests/TestCase.php
- tests/TestClasses/DummySettings.php
Currently if you deploy a new version to a server and the migrations are still running you get a `MissingSettings` exception. For long running migrations and big deployments this can be a problem.
This proposal adds a fallback option to settings defined in the `Settings` object. If you set the default in the code the settings mapper will return that default value instead of throwing an exception. For nullable values the default will be null without changing anything in the `Settings` object.
Example:
```
// Returns false without migrations
public bool $mySetting = false;
// Returns null
public ?string $myOtherSetting;
// Fails
public string $myOtherSetting;
```
What do you think about this proposal?
Credits to @andrasszommer
> Fill missing settings with default values

- src/SettingsConfig.php
- src/SettingsMapper.php
- tests/SettingsTest.php
This pull request is the continuation on the following change: https://github.com/spatie/laravel-settings/pull/298
Based on feedback I've received, we should not allow saving with not migrated default value properties. If the save happens the migration will fail because the row already exists in the database.
also credit to @netpok
> Do not save settings with missing migrations
